Controllers/Customer/MyCartController.cs
using BdShop.Database;
using BdShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Customer
{
    public class MyCartController : Controller
    {
        BdShopEntities db = new BdShopEntities();
        // GET: MyCart
        public ActionResult Index()
        {
            if (Session["username"] != null)
            {
                var data = this.GetDefaultData();

                return View(data);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }


        }

        public ActionResult Remove(int id)
        {
            TempShpData.items.RemoveAll(x => x.ProductID == id);
            return RedirectToAction("Index");

        }
        [HttpPost]
        public ActionResult ProcedToCheckout(FormCollection formcoll)
        {
            var a = TempShpData.items.ToList();
            for (int i = 0; i < formcoll.Count / 2; i++)
            {

                int pID = Convert.ToInt32(formcoll["shcartID-" + i + ""]);
                var ODetails = TempShpData.items.FirstOrDefault(x => x.ProductID == pID);


                int qty = Convert.ToInt32(formcoll["Qty-" + i + ""]);
                ODetails.Quantity = qty;
                ODetails.UnitPrice = ODetails.UnitPrice;
                ODetails.TotalAmount = qty * ODetails.UnitPrice;
                TempShpData.items.RemoveAll(x => x.ProductID == pID);

                if (TempShpData.items == null)
                {
                    TempShpData.items = new List<OrderDetail>();
                }
                TempShpData.items.Add(ODetails);

            }

            return RedirectToAction("Index", "CheckOut");
        }
    }
}

Controllers/Customer/ProductsController.cs
using BdShop.Database;
using BdShop.Models;
using PagedList;
using PagedList.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Customer
{
    public class ProductsController : Controller
    {
        
        BdShopEntities db = new BdShopEntities();
        public ActionResult Index()
        {
            ViewBag.Categories = db.Categories.Select(x => x.CategoryName).ToList();

            ViewBag.TopRatedProducts = TopSoldProducts();
            ViewBag.RecentViewsProducts = RecentViewProducts().Take(3);

            return View("Products");
        }

        //TOP SOLD PRODUCTS
        public List<TopSoldProduct> TopSoldProducts()
        {
            var prodList = (from prod in db.OrderDetails
                            select new { prod.ProductID, prod.Quantity } into p
                            group p by p.ProductID into g
                            select new
                            {
                                pID = g.Key,
                                sold = g.Sum(x => x.Quantity)
                            }).OrderByDescending(y => y.sold).Take(3).ToList();



            List<TopSoldProduct> topSoldProds = new List<TopSoldProduct>();
            if(topSoldProds.Count>0)
            {
                for (int i = 0; i < 3; i++)
                {
                    topSoldProds.Add(new TopSoldProduct()
                    {
                        product = db.Products.Find(prodList[i].pID),
                        CountSold = Convert.ToInt32(prodList[i].sold)
                    });
                }

            }
           
            return topSoldProds;
        }
        //RECENT VIEWS PRODUCTS
        public IEnumerable<Product> RecentViewProducts()
        {
            if (TempShpData.UserID > 0)
            {
                var top3Products = (from recent in db.RecentlyViews
                                    where recent.UserID == TempShpData.UserID
                                    orderby recent.ViewDate descending
                                    select recent.ProductID).ToList().Take(8);

                var recentViewProd = db.Products.Where(x => top3Products.Contains(x.ProductID));
                return recentViewProd;
            }
            else
            {
                var prod = (from p in db.Products
                            select p).OrderByDescending(x => x.UnitPrice).Take(3).ToList();
                return prod;
            }
        }

        
        //ADD TO CART
        public ActionResult AddToCart(int id)
        {
           
            OrderDetail OD = new OrderDetail();
            OD.ProductID = id;
            int Qty = 1;
            int price = (int)db.Products.Find(id).UnitPrice;
            OD.Quantity = Convert.ToInt32(Qty);
            OD.UnitPrice = price;
            OD.TotalAmount = OD.UnitPrice * OD.Quantity;
            OD.Product = db.Products.Find(id);

            if (TempShpData.items == null)
            {
                TempShpData.items = new List<OrderDetail>();
            }
            TempShpData.items.Add(OD);
            AddRecentViewProduct(id);
            return Redirect(TempData["returnURL"].ToString());

        }

        //VIEW DETAILS
        public ActionResult ViewDetails(int id)
        {
            var prod = db.Products.Find(id);
            var reviews = db.Reviews.Where(x => x.ProductID == id).ToList();
            ViewBag.Reviews = reviews;
            ViewBag.TotalReviews = reviews.Count();
            ViewBag.RelatedProducts = db.Products.Where(y => y.CategoryID == prod.CategoryID).ToList();
            AddRecentViewProduct(id);

            var ratedProd = db.Reviews.Where(x => x.ProductID == id).ToList();
            int count = ratedProd.Count();
            int TotalRate = ratedProd.Sum(x => x.Rate).GetValueOrDefault();
            ViewBag.AvgRate = TotalRate > 0 ? TotalRate / count : 0;

            this.GetDefaultData();
            return View(prod);
        }

        //WISHLIST
        public ActionResult WishList(int id)
        {

            Wishlist wl = new Wishlist();
            wl.ProductID = id;
            wl.UserID = TempShpData.UserID;

            db.Wishlists.Add(wl);
            db.SaveChanges();
            AddRecentViewProduct(id);
            ViewBag.WlItemsNo = db.Wishlists.Where(x => x.UserID == TempShpData.UserID).ToList().Count();
            if (TempData["returnURL"].ToString() == "/")
            {
                return RedirectToAction("Index", "Home");
            }
            return Redirect(TempData["returnURL"].ToString());
        }

        //ADD RECENT VIEWS PRODUCT IN DB
        public void AddRecentViewProduct(int? pid)
        {
            if (TempShpData.UserID > 0)
            {
                RecentlyView Rv = new RecentlyView();
                Rv.UserID = TempShpData.UserID;
                Rv.ProductID = pid;
                Rv.ViewDate = DateTime.Now;
                db.RecentlyViews.Add(Rv);
                db.SaveChanges();
            }
        }

        //ADD REVIEWS ABOUT PRODUCT
        public ActionResult AddReview(int productID, FormCollection getReview)
        {

            Review r = new Review();
            r.UserID = TempShpData.UserID;
            r.ProductID = productID;
            r.Username = getReview["name"];
            r.Email = getReview["email"];
            r.Review1 = getReview["message"];
            r.Rate = Convert.ToInt32(getReview["rate"]);
            r.DateTime = DateTime.Now;

            db.Reviews.Add(r);
            db.SaveChanges();
            return RedirectToAction("ViewDetails/" + productID + "");

        }


        public ActionResult Products(int? subCatID)
        {
            ViewBag.Categories = db.Categories.Select(x => x.CategoryName).ToList();
            var prods = db.Products.Where(y => y.CategoryID == subCatID).ToList();
            return View(prods);
        }

        //GET PRODUCTS BY CATEGORY
        public ActionResult GetProductsByCategory(string categoryName, int? page)
        {
            ViewBag.Categories = db.Categories.Select(x => x.CategoryName).ToList();
            ViewBag.TopRatedProducts = TopSoldProducts();

            ViewBag.RecentViewsProducts = RecentViewProducts();
            ViewBag.GetProductsByCategory = true;

            var prods = db.Products.Where(x => x.Category.CategoryName == categoryName).ToList();
            return View("Products", prods.ToPagedList(page ?? 1, 9));
        }
        

        //SEARCH BAR
        public ActionResult Search(string product, int? page)
        {
            ViewBag.Categories = db.Categories.Select(x => x.CategoryName).ToList();
            ViewBag.TopRatedProducts = TopSoldProducts();

            ViewBag.RecentViewsProducts = RecentViewProducts();

            List<Product> products;
            if (!string.IsNullOrEmpty(product))
            {
                products = db.Products.Where(x => x.ProductName.StartsWith(product)).ToList();
            }
            else
            {
                products = db.Products.ToList();
            }
            return View("Products", products.ToPagedList(page ?? 1, 6));
        }

        public JsonResult GetProducts(string term)
        {
            List<string> prodNames = db.Products.Where(x => x.ProductName.StartsWith(term)).Select(y => y.ProductName).ToList();
            return Json(prodNames, JsonRequestBehavior.AllowGet);

        }
        public ActionResult FilterByPrice(int minPrice, int maxPrice, int? page)
        {
            ViewBag.Categories = db.Categories.Select(x => x.CategoryName).ToList();
            ViewBag.TopRatedProducts = TopSoldProducts();

            ViewBag.RecentViewsProducts = RecentViewProducts();
            ViewBag.filterByPrice = true;
            var filterProducts = db.Products.Where(x => x.UnitPrice >= minPrice && x.UnitPrice <= maxPrice).ToList();
            return View("Products", filterProducts.ToPagedList(page ?? 1, 9));
        }


    }
}

Controllers/Owner/DashboardController.cs
using BdShop.Database;
using BdShop.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Owner
{
    public class DashboardController : Controller
    {
        BdShopEntities db = new BdShopEntities();
        // GET: Dashboard
        public ActionResult Index()
        {
            if(Session["sellername"]!=null)
            {
                ViewBag.latestOrders = db.Ordereds.OrderByDescending(x => x.OrderedID).Take(10).ToList();
                ViewBag.NewOrders = db.Ordereds.Where(a => /*a.Dispatched == false &&*/(a.Shipped == false || a.Shipped == null) && (a.Deliver == false || a.Deliver == null) && (a.CancelOrder == false || a.CancelOrder == null)).Count();
                //ViewBag.DispatchedOrders = db.Ordereds.Where(a => a.Dispatched == true && a.Shipped == false && a.Deliver == false).Count();
                ViewBag.ShippedOrders = db.Ordereds.Where(a => /*a.Dispatched == true &&*/ a.Shipped == true && (a.Deliver == false || a.Deliver == null)).Count();
                ViewBag.DeliveredOrders = db.Ordereds.Where(a => /*a.Dispatched == true &&*/ a.Shipped == true && a.Deliver == true).Count();
                ViewBag.CancleOrders = db.Ordereds.Where(a => /*a.Dispatched == true &&*/ /*a.Shipped == true &&*/ a.CancelOrder == true).Count();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "SAccount");
            }
           
        }

        public ActionResult MyProfile()
        {
            if (Session["sellername"] != null)
            {
                var usr = db.Sellers.Find(Session["sid"]);
                return View(usr);
            }
            //this.GetDefaultData();
            else
            {
                return RedirectToAction("Login", "SAccount");
            }

        }

       

    }
}

Controllers/Owner/ProductController.cs
using BdShop.Database;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Owner
{
    public class ProductController : Controller
    {
        // GET: Product
        BdShopEntities db = new BdShopEntities();
        // GET: Product
        public ActionResult Index()
        {
            if (Session["sellername"] != null)
            {
                var query = db.Products.ToList();
                return View(query);
            }
            
              else
            {
                return RedirectToAction("Login", "SAccount");
            }
        }


        public ActionResult Create()
        {
            if (Session["sellername"] != null)
            {
                List<Category> CategoryList = db.Categories.ToList();
                ViewBag.CategoryList = new SelectList(CategoryList, "CategoryID", "CategoryName");
                //GetViewBagData();
                return View();
            }
                
              else
            {
                return RedirectToAction("Login", "SAccount");
            }
        }

        [HttpPost]
        public ActionResult Create(Product prod, HttpPostedFileBase Image)
        {
            List<Category> CategoryList = db.Categories.ToList();
            ViewBag.CategoryList = new SelectList(CategoryList, "CategoryID", "CategoryName");
            if (!ModelState.IsValid)
            {
                prod.CreatedDate = DateTime.Now;
                prod.Picture1 = Image.FileName.ToString();

                var folder = Server.MapPath("~/Uploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));
                db.Products.Add(prod);
                db.SaveChanges();
                return RedirectToAction("Index", "Product");
            }
            //GetViewBagData();
            return View();
        }

        //Get Edit
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (Session["sellername"] != null)
            {
                var query = db.Products.Where(m => m.ProductID == id).ToList().SingleOrDefault();

                if (query == null)
                {
                    return HttpNotFound();
                }
                List<Category> CategoryList = db.Categories.ToList();
                ViewBag.CategoryList = new SelectList(CategoryList, "CategoryID", "CategoryName");
                //GetViewBagData();
                return View(query);
            }
               
              else
            {
                return RedirectToAction("Login", "SAccount");
            }

        }

        //Post Edit
        [HttpPost]
        public ActionResult Edit(Product prod, HttpPostedFileBase Image)
        {
            //GetViewBagData();
            var p = new Product();
            List<Category> CategoryList = db.Categories.ToList();
            ViewBag.CategoryList = new SelectList(CategoryList, "CategoryID", "CategoryName");
            try
            {
                
                prod.ModifiedDate = DateTime.Now;
                prod.Picture1 = Image.FileName.ToString();
                var folder = Server.MapPath("~/Uploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));
                db.Entry(prod).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Product");
            }
            catch
            {
                TempData["msg"] = "Product isn't updated!" +
                    "You must update the product Image..";
                return RedirectToAction("Edit", "Product");
            }
        }

        public ActionResult Delete(int id)
        {
            var query = db.Products.SingleOrDefault(m => m.ProductID == id);
            db.Products.Remove(query);
            db.SaveChanges();
            return RedirectToAction("Index", "Product");
        }


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Bd Shop</title>
    <!-- Bootstrap core CSS-->

    <link href="~/AdminStyle/vendor/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <!-- Custom fonts for this template-->
    <link href="~/AdminStyle/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="~/AdminStyle/vendor/datatables/dataTables.bootstrap4.css" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="~/AdminStyle/css/sb-admin.css" rel="stylesheet">
</head>
<body id="page-top">
    <nav class="navbar navbar-expand navbar-dark bg-dark static-top">
        <a class="navbar-brand mr-1" href="@(Session["sellername"] != null ? Url.Action("Index", "Dashboard") : Url.Action("Login", "SAccount"))" type="button">My Shop</a>
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <!-- Navbar Search -->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </form>
        <!-- Navbar -->
        <ul class="navbar-nav ml-auto ml-md-0">

            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user-circle fa-fw"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Seller Name: @Session["sellername"] </a>
                    <a class="dropdown-item" href="@(Session["sellername"] != null ? Url.Action("Index", "SAccount") : Url.Action("Login", "SAccount"))" type="button">My Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="@Url.Action("Logout","SAccount")" data-toggle="modal" data-target="#logoutModal">Logout</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@(Session["sellername"] != null ? Url.Action("Index", "Dashboard") : Url.Action("Login", "SAccount"))" type="button">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            @*<li class="nav-item">
                <a class="nav-link" href="@(Session["sellername"] != null ? Url.Action("Index", "District") : Url.Action("Login", "SAccount"))" type="button">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Districts</span>
                </a>
            </li>*@

            <li class="nav-item">
                <a class="nav-link" href="@(Session["sellername"] != null ? Url.Action("Index", "Category") : Url.Action("Login", "SAccount"))" type="button">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Categories</span>
                </a>
            </li>



            <li class="nav-item">
                <a class="nav-link" href="@(Session["sellername"] != null ? Url.Action("Index", "Product") : Url.Action("Login", "SAccount"))" type="button">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Products</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="@(Session["sellername"] != null ? Url.Action("Index", "Order") : Url.Action("Login", "SAccount"))" type="button">
                    <i class="fas fa-fw fa-table"></i>
                    <span>All Orders</span>
                </a>
            </li>



        </ul>
        <div id="content-wrapper">

            <!-- Icon Cards-->
            @RenderBody()




            <!-- /.container-fluid -->
            <!-- Sticky Footer -->
            <footer class="sticky-footer">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        Copyright ©
                        <script>document.write(new Date().getFullYear());</script> All rights reserved  by Sourav Kundu <i class="icon-heart color-danger" aria-hidden="true"></i>
                    </div>
                </div>
            </footer>
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-warning" href="@Url.Action("Logout","SAccount")">Logout</a>
                </div>
            </div>
        </div>
    </div>




</body>

</html>

<!-- Bootstrap core JavaScript-->
<script src="~/AdminStyle/vendor/jquery/jquery.min.js"></script>
<script src="~/AdminStyle/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="~/AdminStyle/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="~/AdminStyle/vendor/chart.js/Chart.min.js"></script>
<script src="~/AdminStyle/vendor/datatables/jquery.dataTables.js"></script>
<script src="~/AdminStyle/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="~/AdminStyle/js/sb-admin.min.js"></script>
<!-- Demo scripts for this page-->
<script src="~/AdminStyle/js/demo/datatables-demo.js"></script>
<script src="~/AdminStyle/js/demo/chart-area-demo.js"></script>

Views/Shared/_CartBox.cshtml
@if (@ViewBag.cartBox != null)
{

    foreach (var item in @ViewBag.cartBox)
    {
<li>
    <a class="aa-cartbox-img" href="#"><img src="~/Uploads/@Url.Content(item.Product.Picture1)" alt="@item.Product.AltText"></a>
    <div class="aa-cartbox-info">
        @*<h4><a href="#">@item.ProductID</a></h4>*@
        <h4> </h4>
        <p>@item.Quantity x @item.TotalAmount</p>
    </div>
    <a class="aa-remove-product" href="@Url.Action("Remove", "MyCart", new { id=item.ProductID})"><span class="fa fa-times"></span></a>
</li>}
}
<li>
    <span class="aa-cartbox-total-title">
        Total
    </span>
    <span class="aa-cartbox-total-price">
        @ViewBag.Total
    </span>
</li>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_Product.cshtml
@model BdShop.Database.Product

@*@if (Model.UnitInStock > 0)
    {
        <a class="aa-add-to-cart-btn" href="@(Session["username"] != null ? Url.Action("AddToCart", "Products", new { id=Model.ProductID}) : Url.Action("Login", "Account"))">Add To Cart</a> }
    else
    {
        <a class="aa-add-to-cart-btn" ))">Add To Cart</a>}*@
<!-- start single product item -->
<li>
    <figure>
        <a class="aa-product-img" href="@Url.Action("ViewDetails", "Products", new { id = Model.ProductID })"><img style="height:300px; width:250px" src="~/Uploads/@Url.Content(Model.Picture1)" alt="@Model.AltText"></a>
        @if (Model.UnitInStock > 0)
        {
            <a class="aa-add-card-btn" href="@(Session["username"] != null ? Url.Action("AddToCart", "Products", new { id = @Model.ProductID }) : Url.Action("Login", "Account"))"><span class="fa fa-shopping-cart"></span>Add To Cart</a>
        }
        else
        {
            <a class="aa-add-card-btn text-danger">Out Of Stock!</a>
        }
        <figcaption>
            <h4 class="aa-product-title"><a href="#">@Model.ProductName</a></h4>
            <h6 class="aa-product-title">(@Model.QuantityPerUnit)</h6>
            <span class="aa-product-price">
                <del>
                    @if (Model.OldPrice != null)
                    {
                        <text>Rs.@Model.OldPrice </text>}
                </del>
            </span>
            <span class="aa-product-price"> RS.@Model.UnitPrice</span>
        </figcaption>
    </figure>
    <div class="aa-product-hvr-content">
        <a href="@(Session["username"]!=null ? Url.Action("WishList","Products", new {id=@Model.ProductID }) :Url.Action("Login","Account"))" data-toggle="tooltip" data-placement="top" title="Add to Wishlist"><span class="fa fa-heart-o"></span></a>
        <a href="@Url.Action("ViewDetails", "Products", new { id = Model.ProductID })" title="View Details" data-toggle="tooltip" data-placement="top"><span class="fa fa-info"></span></a>


    </div>
    @if (Model.AddBadge == true)
    {
        if (Model.OfferBadgeClass == "2")
        {
            <span class="aa-badge aa-sold-out" href="#">@Model.OfferTitle</span>
        }
        else if (Model.OfferBadgeClass == "1")
        {
        <span class="aa-badge aa-sale" href="#">@Model.OfferTitle</span>
        }
    }

    @{ TempData["returnURL"] = Request.RawUrl; }
</li>