Controllers/Customer/WishListController.cs
using BdShop.Database;
using BdShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Customer
{
    public class WishListController : Controller
    {
        BdShopEntities db = new BdShopEntities();
        // GET: WishList
        public ActionResult Index()
        {
            if (Session["username"] != null)
            {
                this.GetDefaultData();

                var wishlistProducts = db.Wishlists.Where(x => x.UserID == TempShpData.UserID).ToList();
                return View(wishlistProducts);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }

           
        }

        //REMOVE ITEM FROM WISHLIST
        public ActionResult Remove(int id)
        {
            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");

        }
        //ADD TO CART WISHLIST
        public ActionResult AddToCart(int id)
        {
            OrderDetail OD = new OrderDetail();

            int pid = (int)db.Wishlists.Find(id).ProductID;
            OD.ProductID = pid;
            int Qty = 1;
            decimal price = (decimal)db.Products.Find(pid).UnitPrice;
            OD.Quantity = Qty;
            OD.UnitPrice = price;
            OD.TotalAmount = Qty * price;
            OD.Product = db.Products.Find(pid);

            if (TempShpData.items == null)
            {
                TempShpData.items = new List<OrderDetail>();
            }
            TempShpData.items.Add(OD);

            db.Wishlists.Remove(db.Wishlists.Find(id));
            db.SaveChanges();

            return Redirect(TempData["returnURL"].ToString());

        }
    }
}

Views/WishList/Index.cshtml
@model IEnumerable<BdShop.Database.Wishlist>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="~/Content/img/fashion/fashion-header-bg-8.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>Wishlist Page</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Wishlist</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<!-- Cart view section -->
<section id="cart-view">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="cart-view-area">
                    <div class="cart-view-table aa-wishlist-table">
                        <form action="">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Remove</th>
                                            <th>Image</th>
                                            <th>Product</th>
                                            <th>Price</th>
                                            <th>Stock Status</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Session["username"] != null)
                                        {
                                            foreach (var item in Model)
                                            {

                                                <tr>
                                                    <td><a class="remove" href="@Url.Action("Remove", "WishList", new { id=item.WishlistID})"><fa class="fa fa-close"></fa></a></td>
                                                    <td><a href="#"><img src="~/Uploads/@item.Product.Picture1" alt="@item.Product.AltText"></a></td>
                                                    <td><a class="aa-cart-title" href="#">@item.Product.ProductName</a></td>
                                                    <td>@item.Product.UnitPrice</td>
                                                    <td>
                                                        @if (item.Product.UnitInStock > 0)
                                                        {
                                                            <text>In Stock (@item.Product.UnitInStock)</text> }
                                                        else
                                                        { <text>Out of Stock (@item.Product.UnitInStock)</text>}
                                                    </td>
                                                    <td>
                                                        @if (item.Product.UnitInStock > 0)
                                                        {
                                                            <a class="aa-add-to-cart-btn" href="@(Session["username"] != null ? Url.Action("AddToCart", "WishList", new { id=item.WishlistID}) : Url.Action("Login", "Account"))">Add To Cart</a> }
                                                        else
                                                        {
                                                            <a class="aa-add-to-cart-btn" ))">Add To Cart</a>}
                                                    </td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <text>Please login to view wishlist</text>}
                                    </tbody>
                                </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->