Controllers/Customer/MyOrderController.cs
using BdShop.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BdShop.Controllers.Customer
{
    public class MyOrderController : Controller
    {
        BdShopEntities db = new BdShopEntities();
        // GET: MyOrder
        public ActionResult Index(int? id)
        {
            if (Session["username"] != null)
            {
                var query = db.getallorderusers.Where(m => m.UserID == id).ToList();
                return View(query);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
           

        }

        public ActionResult Details(int? id)
        {
            if (Session["username"] != null)
            {
                Ordered ord = db.Ordereds.Find(id);
                var Ord_details = db.OrderDetails.Where(x => x.OrderedID == id).ToList();
                var tuple = new Tuple<Ordered, IEnumerable<OrderDetail>>(ord, Ord_details);

                double SumAmount = Convert.ToDouble(Ord_details.Sum(x => x.TotalAmount));
                ViewBag.TotalItems = Ord_details.Sum(x => x.Quantity);
                ViewBag.Discount = 0;
                ViewBag.ShippingCost = 50;
                ViewBag.TAmount = SumAmount - 0 + 50;
                ViewBag.Amount = SumAmount;
                return View(tuple);
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
            
        }
    }
}

Views/MyOrder/Details.cshtml
@using BdShop.Database;
@model Tuple<Ordered, IEnumerable<OrderDetail>>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="~/Content/img/fashion/fashion-header-bg-8.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>My Orders</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Orders</a></li>
                    <li class="active">Order Detail</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<div class="container">

    <div class="col-md-12">
        <div class="cart-view-area">
            <i class="cart-view-table"></i>
            <h3 class="text-black-50"><strong>Customer Details:</strong></h3>
            @*<a href="../Product/Create" class="btn btn-info pull-right fa fa-plus">Add New</a>*@
        </div>
        @*<table>
                <tr>
                    <th colspan="-4">Order Id:</th>
                    <td>@Model.Item1.OrderID</td>
                </tr>
                <tr>
                    <th>Customer Name:</th>
                    <td>@Model.Item1.User.FirstName</td>
                </tr>
            </table>*@
        <div class="row">
            <div class="col-md-6">
                <dl class="d-lg-table-cell ">
                    <dt>
                        @Html.DisplayName("Order ID  ") : @Html.DisplayFor(model => model.Item1.OrderedID)
                    </dt>

                    <dt>
                        @Html.DisplayName("Customer Name ") : @Html.DisplayFor(model => model.Item1.ShippingDetail.FirstName) @Html.DisplayFor(model => model.Item1.ShippingDetail.LastName)
                    </dt>

                    @*<dt>
                            @Html.DisplayName("Customer Address : ")
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Item1.User.Address)
                        </dd>*@
                    <dt>
                        @Html.DisplayName("Contact No ") : @Html.DisplayFor(model => model.Item1.ShippingDetail.Mobile)
                    </dt>

                    <dt>
                        @Html.DisplayName("Payment Type ") : @Html.DisplayFor(model => model.Item1.Payment.PaymentType1.PaymentTypeName)
                    </dt>

                    <dt>
                        @Html.DisplayName("Address ") : @Html.DisplayFor(model => model.Item1.ShippingDetail.Address)
                    </dt>
                    <dt>
                        @Html.DisplayName("Post Code ") : @Html.DisplayFor(model => model.Item1.ShippingDetail.PostalCode)
                    </dt>

                </dl>
            </div>

        </div>
    </div>
</div>


<!-- Cart view section -->
<section id="cart-view">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="cart-view-area">
                    <h3><strong>Product Detail:</strong></h3>
                    @using (Html.BeginForm("Details", "MyOrder", FormMethod.Post))
                    {
                        <div class="cart-view-table">
                            <form action="">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th>S.No</th>
                                                <th>Product Name</th>
                                                <th>Quantity</th>
                                                <th>Unit Price</th>
                                                <th>Total</th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            @{int i = 0;}
                                            @foreach (var item in Model.Item2)
                                            {
                                                i++;
                                                <tr>
                                                    <td>@i.ToString()</td>
                                                    <td>@item.Product.ProductName</td>
                                                    <td>@item.Quantity</td>
                                                    <td>@item.UnitPrice</td>
                                                    <td>@item.TotalAmount</td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                    <td colspan="5"><h2></h2></td>

                                                </tr>
                                                <tr>
                                                    <th> </th>
                                                    <th> </th>

                                                    <th class="text-center">@ViewBag.TotalItems</th>
                                                    <th></th>
                                                    <th class="text-center">@ViewBag.Amount </th>
                                                </tr>
                                                <tr>
                                                    <th>Shipping Cost</th>
                                                    <th colspan="3"></th>
                                                    <th class="text-center">@ViewBag.ShippingCost</th>
                                                </tr>
                                            <tr class="bg-info">
                                                <th>Total Amount</th>
                                                <th colspan="3"></th>
                                                <th class="text-center">@ViewBag.TAmount</th>
                                            </tr>



                                        </tfoot>

                                    </table>
                                </div>
                                @*</div>
                                            </div>
                                        </div>
                                    </div>*@

                                <a onclick="window.history.back();" class="btn btn-warning">Back</a>
                            </form>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->

Views/MyOrder/Index.cshtml
@model List<BdShop.Database.getallorderuser>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- catg header banner section -->
<section id="aa-catg-head-banner">
    <img src="~/Content/img/fashion/fashion-header-bg-8.jpg" alt="fashion img">
    <div class="aa-catg-head-banner-area">
        <div class="container">
            <div class="aa-catg-head-banner-content">
                <h2>My Orders</h2>
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li class="active">Orders</li>
                </ol>
            </div>
        </div>
    </div>
</section>
<!-- / catg header banner section -->
<!-- Cart view section -->
<section id="cart-view">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="cart-view-area">
                    @using (Html.BeginForm("Index", "MyOrder", FormMethod.Post))
                    {
                        <div class="cart-view-table">
                            <form action="">
                                <div class="table-responsive">
                                    <table class="table">
                                        <thead>
                                            <tr>

                                                <th>Serial No.</th>
                                                <th>Order ID</th>
                                                <th>Total Amount</th>
                                                <th>Order Date</th>
                                                <th>Status</th>
                                                <th>Date & Time</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>

                                            @foreach (var item in Model)
                                            {
                                            <tr>
                                                <td>@(Model.IndexOf(item)+1)</td>

                                                <td>@item.OrderedID</td>
                                                <td>@item.TotalAmount</td>
                                                <td>@item.OrderDate</td>
                                                @if (item.Shipped == true && item.Deliver == false)
                                                {
                                                    <td>Shipped</td>
                                                }
                                                else if (item.Shipped == true && item.Deliver == true)
                                                {
                                                    <td>Delivered</td>

                                                }
                                                else if (item.CancelOrder == true)
                                                {
                                                    <td>Cancled</td>

                                                }
                                                else
                                                {
                                                    <td>On Process</td>

                                                }


                                                @if (item.Shipped == true && item.Deliver == false)
                                                {
                                                    <td>Shipping On :@item.ShippedDate</td>
                                                }
                                                else if (item.Shipped == true && item.Deliver == true)
                                                {
                                                    <td>Delivered On :@item.DeliveryDate</td>

                                                }
                                                else if (item.CancelOrder == true)
                                                {
                                                    <td>Cancled On : @item.CancelDate</td>

                                                }
                                                else
                                                {
                                                    <td> </td>
                                                }


                                                <td>

                                                    @*<a href="@Url.Action("Edit", "Order", new { id = item.OrderedID})" class="btn btn-primary">Edit</a>*@
                                                    <a href="@Url.Action("Details", "MyOrder", new { id = item.OrderedID})" class="btn btn-warning">Details</a>


                                                </td>
                                            </tr>
                                            }


                                        </tbody>

                                        @*<tr>
                                                <td colspan="5"><button type="submit" class="aa-cart-view-btn">Proced to Checkout</button></td>
                                            </tr>*@
                                    </table>
                                </div>
                            </form>
                            <!-- Cart Total view -->
                            @*<div class="cart-view-total">
                                    <h4>Cart Totals</h4>
                                    <table class="aa-totals-table">
                                        <tbody>
                                            <tr>
                                                    <th>Subtotal</th>
                                                    <td id="subTotal">00</td>
                                                </tr>
                                                <tr>
                                                    <th>Discount</th>
                                                    <td id="discount">0</td>
                                                </tr>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <th>Total Amount</th>
                                                    <td id="totalAmount">@item.TotalAmount</td>
                                                </tr>
                                            }
                                        </tbody>
                                        <tfoot>

                                            <tr>
                                                <td colspan="3"><button type="submit" class="aa-cart-view-btn">Proced to Checkout</button></td>
                                            </tr>

                                        </tfoot>
                                    </table>

                                </div>*@
                        </div>}
                </div>
            </div>
        </div>
    </div>
</section>
<!-- / Cart view section -->